35 investigate migrating to meson [WIP]
OpenPIV/openpiv-c--qt pull request #44
Opened 2024-03-15 04:58 UTC by ErichZimmer

## NOTICE:
This pull request commits significant changes to the project. As such, it is important to review all changes cerefully.

## Preface
The Meson build system offers a concise and effect way to compile applications and libraries. As it is a newer build system using modern Python, it avoids some pitfalls associated with CMake. Additionally, it offers native cross-compilation through the use of cross-compilation build files. 

## New:
 * `subprojects` folder contains most external dependencies
## Changes:
 * Build system is now based on Meson
 * `test` directory was renamed to `tests`
 
## Work in Progress
 * meson.build files for benchmarks need to be fixed
 * Executables hang after completion on Windows when using MinGW (this is a MinGW problem)
 * Add support for MSVC compiler (requires __declspec(dllexport))
 * Fix merge conflicts

2024-03-18 22:39 UTC, timdewhirst requested changes

2024-03-18 22:39 UTC, timdewhirst commented on README.md
>  * a compiler (e.g. `apt install build-essentials`)
is cmake still required with this migration to meson? I think by default the backend is ninja?

2024-03-18 22:39 UTC, timdewhirst commented on README.md
> +* `meson install -C buildfir --destdir <some directory>` to install in a specifit directory.
s/specifit/specific/

2024-03-18 22:39 UTC, timdewhirst commented on README.md
> +Make sure the prefix, or destdir, is set so binaries are not accidentally installed on the system.
I would hope for unix-like environment permissions would prevent installation!

2024-03-18 22:39 UTC, timdewhirst commented on meson.build
> +elif cpp.get_id() == 'msvc'
it should build fine with msvc - this is the case for the cmake build, so no reason it shouldn't be true for meson!

2024-03-18 22:39 UTC, timdewhirst commented on meson.build
> +pkgconfig.generate(
any way this information can be taken from the project object rather than repeating?

2024-03-20 19:13 UTC, ErichZimmer commented on README.md
>  * a compiler (e.g. `apt install build-essentials`)
In essence, no.

When using Meson, the primary project compilation occurs via Ninja (or any other supported backend). However, some cases warrant the use of CMake. For instance, libraries that do not have a Meson port can still be used through Meson's CMake module (this is important for the future expansion of image loaders). In the context of OpenPIV-c--qt, CMake was used to build and extract the dependency FMT::FMT_HEADER_ONLY because a Meson override defaults to the non-header implementation of the library. This is no longer the case as FMT::FMT_HEADER_ONLY is now extracted through Meson's function subproject().

2024-03-20 19:27 UTC, ErichZimmer commented on README.md
> +* `meson install -C buildfir --destdir <some directory>` to install in a specifit directory.
That typo is fixed. Apparently, I overlooked it when checking for grammatical errors.

2024-03-20 19:43 UTC, ErichZimmer commented on README.md
> +Make sure the prefix, or destdir, is set so binaries are not accidentally installed on the system.
This should not be an issue for Unix. However, Windows is where that warning was primarily targeted for. If not set, Meson defaults to C:/ (or whatever letter the current drive is assigned) which could may cause issues and cluttering of the drive. I can be more explicit on that topic if needed.

2024-03-20 20:57 UTC, ErichZimmer commented on meson.build
> +pkgconfig.generate(
I removed the redundant information through meson project defines.

2024-03-21 01:08 UTC, ErichZimmer commented on meson.build
> +elif cpp.get_id() == 'msvc'
Currently, Meson does not have an option to automatically export symbols on Windows like CMake's WINDOWS_EXPORT_ALL_SYMBOLS (and probably won't have one for a long time, see [#2132](https://github.com/mesonbuild/meson/issues/2132)). This means that by default, MSVC cannot be used unless we manually export public symbols which then can be used to generate an import lib.

2024-03-21 02:35 UTC, ErichZimmer commented on meson.build
> +elif cpp.get_id() == 'msvc'
The compiler outputs 

> fatal error LNK1181: cannot open input file 'openpiv\openpiv.lib'

since no import lib has been generated, One way to fix this issue is to feed a blank import lib into the openpiv_lib target and create the import lib later in the build process.

2024-03-21 06:34 UTC, ErichZimmer commented on meson.build
> +elif cpp.get_id() == 'msvc'
After creating a script that generates an import lib (based on stack overflow), I then get the following error (possibly due to not exporting symbols as that is yet to be done)
> image_algos_test.cpp.obj : error LNK2019: unresolved external symbol "public: __cdecl openpiv::core::rect::rect(class openpiv::core::point<2,int> const &,class openpiv::core::size const &)" (??0rect@core@openpiv@@QEAA@AEBV?$point@$01H@12@AEBVsize@12@@Z) referenced in function "public: class openpiv::core::image<class openpiv::core::complex<double> > & __cdecl openpiv::core::image<class openpiv::core::complex<double> >::operator=<class openpiv::core::image_expression<struct openpiv::core::mult_op<class openpiv::core::complex<double> >,class openpiv::core::image_interface_expression_node<class openpiv::core::image,class openpiv::core::complex<double>,class openpiv::core::image<class openpiv::core::complex<double> > >,class openpiv::core::unary_image_expression<struct openpiv::core::conjugate_op<class openpiv::core::complex<double> >,class openpiv::core::image_interface_expression_node<class openpiv::core::image,class openpiv::core::complex<double>,class openpiv::core::image<class openpiv::core::complex<double> > > > >,void>(class openpiv::core::image_expression<struct openpiv::core::mult_op<class openpiv::core::complex<double> >,class openpiv::core::image_interface_expression_node<class openpiv::core::image,class openpiv::core::complex<double>,class openpiv::core::image<class openpiv::core::complex<double> > >,class openpiv::core::unary_image_expression<struct openpiv::core::conjugate_op<class openpiv::core::complex<double> >,class openpiv::core::image_interface_expression_node<class openpiv::core::image,class openpiv::core::complex<double>,class openpiv::core::image<class openpiv::core::complex<double> > > > > const &)" (??$?4V?$image_expression@U?$mult_op@V?$complex@N@core@openpiv@@@core@openpiv@@V?$image_interface_expression_node@Vimage@core@openpiv@@V?$complex@N@23@V?$image@V?$complex@N@core@openpiv@@@23@@23@V?$unary_image_expression@U?$conjugate_op@V?$complex@N@core@openpiv@@@core@openpiv@@V?$image_interface_expression_node@Vimage@core@openpiv@@V?$complex@N@23@V?$image@V?$complex@N@core@openpiv@@@23@@23@@23@@core@openpiv@@X@?$image@V?$complex@N@core@openpiv@@@core@openpiv@@QEAAAEAV012@AEBV?$image_expression@U?$mult_op@V?$complex@N@core@openpiv@@@core@openpiv@@V?$image_interface_expression_node@Vimage@core@openpiv@@V?$complex@N@23@V?$image@V?$complex@N@core@openpiv@@@23@@23@V?$unary_image_expression@U?$conjugate_op@V?$complex@N@core@openpiv@@@core@openpiv@@V?$image_interface_expression_node@Vimage@core@openpiv@@V?$complex@N@23@V?$image@V?$complex@N@core@openpiv@@@23@@23@@23@@12@@Z)

2024-03-24 16:45 UTC, timdewhirst commented on meson.build
> +elif cpp.get_id() == 'msvc'
okay, that's one for me to follow up on. Thanks!

2024-03-24 16:49 UTC, timdewhirst commented on meson.build
> +elif cpp.get_id() == 'msvc'
tracked by #45

2024-03-24 16:49 UTC, merged